@startuml

skinparam monochrome true
title Основной поток оформления заказа

actor Клиент
participant "Сайт" as site
participant "Система" as sys
participant "Склад" as warehouse
participant "Банк" as bank

Клиент -> site: Регистрация или авторизация
activate site
site -> sys: Подтверждение данных
activate sys
sys --> Клиент: Данные подтверждены
deactivate sys
deactivate site

Клиент -> site: Выбор товаров, оформление заказа
activate site
site -> sys: Передача информации о заказе
activate sys
sys -> warehouse: Проверка наличия товаров
activate warehouse
warehouse -> sys: Результаты проверки
deactivate warehouse
sys -> site: Уведомление о результатах проверки
deactivate sys
site --> Клиент: Заказ сформирован
deactivate site

Клиент -> site: Выбор способа оплаты
activate site
site -> sys: Передача информации о платеже
activate sys
sys -> bank: Проведение транзакции
activate bank
bank -> sys: Результат транзакции
deactivate bank
sys -> site: Результат платежа
deactivate sys
site --> Клиент: Платеж обработан
deactivate site

Клиент -> site: Получение квитанции и статуса заказа
activate site
site -> sys: Формирование квитанции и статуса
activate sys
sys -> warehouse: Инструкция по подготовке товара
activate warehouse
warehouse -> sys: Подтверждение готовности товара
deactivate warehouse
sys -> site: Обновление статуса заказа
deactivate sys
site --> Клиент: Заказ отправлен на обработку
deactivate site

@enduml
